---
- hosts: droplets
  tasks:
    - name: Installing nodeJs
      apt: pkg=nodejs state=installed update_cache=true

    - name: Installing npm
      apt: pkg=npm state=installed update_cache=true

    - name: Installing unzip
      apt: pkg=unzip state=installed update_cache=true

    - name: Linking nodejs to run as "node"
      command: ln -s /usr/bin/nodejs /usr/bin/node

    - name: "Install forever (to run Node.js app)."
      npm: name=forever global=yes state=latest

    - name: unzip Proxy and copy to destination
      unarchive: src='Proxy.zip' dest='/' copy='yes'

    - name: npm install
      npm: path=/Proxy

    - name: Start serverDown
      command: sudo forever start /Proxy/serverDown.js

    - name: Start proxy server
      command: sudo forever start /Proxy/proxyServer.js